### ISSUE TITLE
Implicit declaration of function Remove_duplicate_shortcuts

### ISSUE THREAD

**Issue by GoogleCodeExporter** [birdal46/grafx2#430]
```
I've just updated the gentoo ebuild to work with grafx2-2.3.1771 
and at the end of the compilation the system outputted me this:


 * QA Notice: Package has poor programming practices which may compile
 *            fine but exhibit random runtime failures.
 * main.c:664: warning: implicit declaration of function ‘Remove_duplicate_shortcuts’

 * Please do not file a Gentoo bug and instead report the above QA
 * issues directly to the upstream developers of this software.
 * Homepage: http://code.google.com/p/grafx2/

A quick smoke test on the program, proved to work fine, so this isn't urgent at 
all.

Thanks.
```

Original issue reported on code.google.com by `00.rgb.s...@gmail.com` on 10 Apr 2011 at 10:59

**Comment by GoogleCodeExporter** [comment]
```
Likely a missing include.
```

Original comment by `pulkoma...@gmail.com` on 10 Apr 2011 at 11:27

**Comment by GoogleCodeExporter** [comment]
```
Indeed, I should have added #include "help.h" in main.c . The call matches the 
prototype, so afaik it doesn't have any bad consequences. (If somebody fixes, 
don't forget to regenerate dependencies: make depend)
2.25Mb source code that compiles with -W -Wall and gets 1 warning, "poor 
programming practices" ? Aww man! :)

```

Original comment by `yrizoud` on 10 Apr 2011 at 1:58
- Changed state: **Accepted**
- Added labels: **OpSys-All**
- Removed labels: **OpSys-**

**Comment by GoogleCodeExporter** [comment]
```
lol, well it's automated, and I don't expect machines to be sensitive ;)
```

Original comment by `00.rgb.s...@gmail.com` on 10 Apr 2011 at 2:34

**Comment by GoogleCodeExporter** [comment]
```
Fixed in r1774. 
```

Original comment by `yrizoud` on 10 Apr 2011 at 2:39

**Comment by GoogleCodeExporter** [comment]
Original comment by `yrizoud` on 10 Apr 2011 at 2:39
- Changed state: **Fixed**
